########################################### Calculate TCs ######################
# This script calculates transfer coefficients from the output files generated
# by running the DPMFA model. 

# Load libraries
library(tidyverse)
library(sensitivity)
library(ggplot2)
library(ks) 

################################ Load data #####################################
# set environment
env = "OOD"
#env = "HPC"

# set path to the 'output' folder generated by the DPMFA_NL_EU model
if(env == "OOD"){
  data_folder <- "/rivm/r/E121554 LEON-T/03 - uitvoering WP3/DPMFA_textiel/Output"
} else {
  data_folder <- "S:/BioGrid/hidsa/DPMFA_output/"
}

ModelRun = "PMFA_data_NL2025_07_17"

load(file = paste0(data_folder,"/",ModelRun,".RData"))  # DPMFA_inflow is read in

################## Prepare data for calculating probability Y ##################

SelectYear = 2019 # For TC calculation this needs to be set to 2019, otherwise also change below in Line x90!

# Create a dataframe for just SelectYear
data_Year <-  DPMFA_inflow |> 
  unnest(Mass_Polymer_kt, keep_empty = TRUE) |> 
  pivot_longer(cols=-c(Type, Scale, Source, Polymer, To_Compartment, Material_Type, iD_source, RUN),
               names_to = "Year",
               values_to = "Mass_Polymer_kt") |> 
  filter(Year == SelectYear) |>
  mutate(Mass_Polymer_t = Mass_Polymer_kt * 1000) |> # conert kt to ton
  filter(To_Compartment %in% unique(DPMFA_sink$To_Compartment) & Type == "Inflow") |> # only sinks
  mutate(`Environmental_compartment` = # make column indicating of this an air, water or soil sink.
           case_when(
             str_detect(To_Compartment, 'water') ~ "water",
             str_detect(To_Compartment, 'air') ~ "air",
             str_detect(To_Compartment, 'soil') ~ "soil",
             .default = "none"
           )) |> filter(`Environmental_compartment` != "none") |>
  filter(Polymer == "Acryl")

Sink_inflow_polymer_source_scale <- data_Year |> 
  ungroup() |> 
  group_by(Scale, Source,Polymer, RUN, Year, Type) |> 
  summarise(Mass_Polymer_t = sum(Mass_Polymer_t))

Sink_inflow_polymer_source_scale_micro <- data_Year |> 
  ungroup() |> 
  filter(Material_Type == "micro") |> 
  group_by(Scale, Source,Polymer, RUN, Year, Type) |> 
  summarise(Mass_Polymer_t = sum(Mass_Polymer_t))

Sink_inflow_polymer_source_scale_macro <- data_Year |> 
  ungroup() |> 
  filter(Material_Type == "macro") |> 
  group_by(Scale, Source,Polymer, RUN, Year, Type) |> 
  summarise(Mass_Polymer_t = sum(Mass_Polymer_t))

################## Prepare data for calculating probability X ##################
data_TC_outflow <- DPMFA_outflow |> 
  unnest(Mass_Polymer_kt, keep_empty = TRUE) |>
  filter(Polymer == "Acryl")

if(SelectYear != 2019) warning(paste0("Warning: Is the Data for outflow also set to ",SelectYear,"? (if no, please change!"))

totals_TC_outflow <- data_TC_outflow |>
  group_by(From_compartment, RUN,Scale,Polymer,Source) |>
  summarize(Total_from = sum(`2019`)) |> # sum up total outflows per compartment
  ungroup()

TC_outflow <- full_join(totals_TC_outflow, data_TC_outflow) |> # Combines the sum totals with the outflows
  select(RUN, From_compartment,To_compartment, Polymer, Source,Scale, iD_source ,Total_from, `2019`) |> 
  rowwise() |> 
  mutate(TC = `2019` / Total_from)  # calculates the TC per RUN

faultyTCs <- TC_outflow |>   
  group_by(RUN,Polymer,Source,Scale,From_compartment) |> 
  summarise(unitycheck = sum(TC)) |> 
  mutate(unitycheck_rounded = round(unitycheck,digits = 10)) |>  
  filter(unitycheck_rounded != 1)

if(length(faultyTCs$From_compartment) > 0) {
  faultyTCs
  stop("fualty TC's")
}

TC_outflow <-   TC_outflow |>   
  mutate(TC_name = paste0(From_compartment,".2.",To_compartment), # arrange TC names so they are clear
         iD_source = NULL, # remove some redundant columns
         Total_from = NULL, # remove some redundant columns
         `2019` = NULL, # remove some redundant columns
         .keep = "unused")

################################ Define functions ##############################

# Clean up env before calculations
needed_data <- c("data_folder", "ModelRun", "TC_outflow", "Sink_inflow_polymer_source_scale", "Sink_inflow_polymer_source_scale_micro", "Sink_inflow_polymer_source_scale_macro")
to_remove <- setdiff(ls(), needed_data)
rm(list = to_remove)

fprobX_Y <- function(TC_outflow, 
                     Sink_inflow_polymer_source_scale, 
                     iPolymer = "LDPE", 
                     iSource = "Agriculture",
                     iScale = "NL"){
  
  ProbX <- TC_outflow |> 
    filter(Polymer == iPolymer, Source == iSource,Scale == iScale) %>%
    pivot_wider(names_from = TC_name,
                values_from = TC)
  
  ProbX_Y <- Sink_inflow_polymer_source_scale |> 
    filter(Polymer == iPolymer, Source == iSource, Scale == iScale) |> 
    full_join(ProbX)
  
  return(ProbX_Y)
}

fPrepprobX_Y <- function(probX_Y = probX_Y){
  probX_Y <- probX_Y |> 
    ungroup() |> 
    drop_na() |> 
    mutate(Scale = NULL,
           Source  = NULL,
           Polymer = NULL,
           RUN = NULL,
           Year = NULL,
           Type = NULL) |> # remove columns that are not numeric data for probX
    mutate_all(~if_else(. == 0, 1e-20, .)) |> # make 0's very small numbers 1e-20
    mutate_all(log) |> # log transform
    drop_na() |> 
    select(-where(~ var(.) == 0))# remove columns with 0 variance (are constant)
}

# dataX=TC_outflow
# dataY=Sink_inflow_polymer_source_scale
# figureSuffix = NULL
# 
# iScale = "NL"
# iSource = "Import of clothing (EU)"
# iPolymer = "PET"

## function to create sensitivity plots for all output sources, polymer and scale combo's
fSensOut <- function(dataX=TC_outflow, 
                     dataY=Sink_inflow_polymer_source_scale,
                     figureSuffix = NULL){
  
  TCsens_data <- tibble(`TC`=NA, `delta`=NA, `Polymer`=NA, `Scale`=NA, `Source`=NA)
  for(iScale in unique(dataX$Scale)){
    for(iSource in unique(dataX$Source) ){
      for(iPolymer in unique(dataX$Polymer)){
        
        probX_Y <- fprobX_Y(TC_outflow=dataX, 
                            Sink_inflow_polymer_source_scale=dataY, 
                            iPolymer, iSource , iScale)
        if(length(probX_Y$RUN) == 0) next
        
        probX_Y <- fPrepprobX_Y(probX_Y)
        
        probX <- probX_Y |> 
          mutate(Mass_Polymer_t = NULL) |> 
          data.matrix()
        
        probY <- probX_Y |> 
          pull(Mass_Polymer_t )
        
        #run global sensitivity analysis
        m <- sensiFdiv(model = NULL, X=probX, fdiv = "TV", nboot = 0, conf = 0.95,   scale = TRUE)
        tell(m, y=probY,S)
        
        #prepare output for ggplot
        borg_d_temp <- tibble(TC = colnames(probX),
                              delta= m$S$original)
        
        TCdelta_part1 <- borg_d_temp |> 
          mutate(Polymer= iPolymer,
                 Scale = iScale,
                 Source = iSource)
        TCsens_data <-
          TCsens_data |> add_row(TCdelta_part1)}
      
      # Prepare and sort data
      pdata <- TCsens_data |> 
        drop_na() |> 
        filter(Source == iSource) |> 
        arrange(desc(TC))  # Or any other variable you want to use for sorting
      
      n <- nrow(pdata)
      third <- ceiling(n / 3)
      
      # Split into three groups
      pdata1 <- pdata[1:third, ]
      pdata2 <- pdata[(third + 1):(2 * third), ]
      pdata3 <- pdata[(2 * third + 1):n, ]
      
      # Determine fill scale range (constant across all plots)
      delta_range <- range(pdata$delta, na.rm = TRUE)
      
      # Plot 1
      p1 <- ggplot(pdata1, aes(x = Polymer, y = TC, fill = delta)) +
        geom_tile() +
        scale_fill_viridis_c(alpha = 0.5, option = "A", direction = -1,
                             limits = delta_range) +
        theme_light() +
        theme(axis.text.y = element_text(size = 8),
              axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1),
              panel.grid.major = element_blank(),
              panel.grid.minor = element_blank(),
              panel.border = element_blank()) +
        facet_grid(vars(), vars(Source), scales = "free") 
      
      # Plot 2
      p2 <- ggplot(pdata2, aes(x = Polymer, y = TC, fill = delta)) +
        geom_tile() +
        scale_fill_viridis_c(alpha = 0.5, option = "A", direction = -1,
                             limits = delta_range) +
        theme_light() +
        theme(axis.text.y = element_text(size = 8),
              axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1),
              panel.grid.major = element_blank(),
              panel.grid.minor = element_blank(),
              panel.border = element_blank()) +
        facet_grid(vars(), vars(Source), scales = "free")
      
      # Plot 3
      p3 <- ggplot(pdata3, aes(x = Polymer, y = TC, fill = delta)) +
        geom_tile() +
        scale_fill_viridis_c(alpha = 0.5, option = "A", direction = -1,
                             limits = delta_range) +
        theme_light() +
        theme(axis.text.y = element_text(size = 8),
              axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1),
              panel.grid.major = element_blank(),
              panel.grid.minor = element_blank(),
              panel.border = element_blank()) +
        facet_grid(vars(), vars(Source), scales = "free") 
      
      print(p1)
      print(p2)
      print(p3)
      
      ggsave(filename = paste(ModelRun, iScale, iSource, figureSuffix, "totEnvEmis_GSA_plot1.jpg", sep="_"),
             plot = p1,
             device = "jpeg",
             path = paste0(data_folder,"/Figures/Sensitivity_analysis"),
             scale = 2,
             width = 9,
             height = 11,
             units = "cm",
             dpi = 300)
      
      ggsave(filename = paste(ModelRun, iScale, iSource, figureSuffix, "totEnvEmis_GSA_plot2.jpg", sep="_"),
             plot = p2,
             device = "jpeg",
             path = paste0(data_folder,"/Figures/Sensitivity_analysis"),
             scale = 2,
             width = 8,
             height = 11,
             units = "cm",
             dpi = 300)
      
      ggsave(filename = paste(ModelRun, iScale, iSource, figureSuffix, "totEnvEmis_GSA_plot3.jpg", sep="_"),
             plot = p3,
             device = "jpeg",
             path = paste0(data_folder,"/Figures/Sensitivity_analysis"),
             scale = 2,
             width = 8,
             height = 11,
             units = "cm",
             dpi = 300)
    }
  }
  TCsens_data <- TCsens_data |> drop_na()
  return(TCsens_data)
}

# Make plots and save sensitivity data
sensdata_all <- fSensOut (dataX=TC_outflow,
                      dataY=Sink_inflow_polymer_source_scale,
                      figureSuffix = "all")
save(sensdata_all, file = paste0(data_folder, "/GSA/", ModelRun, "_GSA_output_all.RData"))


sensdata_micro <- fSensOut (dataX=TC_outflow,
                      dataY=Sink_inflow_polymer_source_scale_micro,
                      figureSuffix = "micro")
save(sensdata_micro, file = paste0(data_folder, "/GSA/", ModelRun,"_GSA_output_micro.RData"))


sensdata_macro <- fSensOut (dataX=TC_outflow,
                      dataY=Sink_inflow_polymer_source_scale_macro,
                      figureSuffix = "macro")
save(sensdata_macro, file = paste0(data_folder,"/GSA/", ModelRun, "_GSA output_macro.RData"))




