# Script to make RData files from output folder with csv files. 
# Authors: Joris Quik and Anne Hids

# Load packages 
library(tidyverse)
library(readr)

# set environment
#env = "OOD"
env = "HPC"

################################ Load data #####################################
# set path to the 'output' folder generated by the DPMFA_NL_EU model
# if(env == "OOD"){
#   data_folder <- "/rivm/n/hidsa/Documents/DPMFA_textiel/Output_backup"
# } else {
#   #data_folder <- "S:/BioGrid/hidsa/DPMFA_output/"
#   data_folder <- "/data/BioGrid/hidsa/DPMFA_output"
# }

if(env == "OOD"){
  data_folder <- "/rivm/n/hidsa/Documents/DPMFA_textiel/Output_backup"
} else {
  #data_folder <- "S:/BioGrid/hidsa/DPMFA_output/"
  data_folder <- "/data/BioGrid/hidsa/DPMFA_output"
}

# Give the folder name where the output is located
output_folder_name <- "Baseline_NL"


output_folder_path <- paste0(data_folder, "/", output_folder_name)

# Get csv file paths
file_paths <- list.files(path=output_folder_path, pattern = "\\.csv$", recursive=TRUE)
file_pathsdf <- as.data.frame(file_paths)

########################### Get configurations #################################
filename <- paste0(output_folder_path, "/metadata.txt")
f <- readLines(filename, n=13)

ModelRunDate <- grep("Start date and time:",f, value=TRUE)
ModelRunDate <- as.Date(gsub("Start date and time: ", "", ModelRunDate), format = "%d-%m-%Y") 

startyear <- grep("Startyear: ",f, value=TRUE)
startyear <- as.numeric(gsub("Startyear: ", "", startyear))

endyear <- grep("Endyear: ",f, value=TRUE)
endyear <- as.numeric(gsub("Endyear: ", "", endyear))

runs <- grep("Runs: ",f, value=TRUE)
runs <- as.numeric(gsub("Runs: ", "", runs))

modeltype <- grep("Model type: ", f, value=TRUE)
modeltype <- gsub("Model type: ", "", modeltype)
modeltype <- as.character(modeltype)

inputfile <- grep("Maininputfile version: ", f, value=TRUE)
inputfile <- gsub("Maininputfile version: ", "", inputfile)

region <- grep("Region: ", f, value=TRUE)
region <- gsub("Region: ", "", region)

metadata <- list(ModelRunDate = ModelRunDate,
                 startyear = startyear,
                 endyear = endyear,
                 runs = runs,
                 modeltype = modeltype,
                 inputfile = inputfile,
                 region = region)

############################# Define function ##################################
readdelimF <- function(root_folder, FileName, startyear, endyear, runs){
  data <- read_delim(file = paste0(root_folder,"/",FileName),
                     col_names = FALSE,
                     delim = " ",
                     col_types = "d",
                     n_max = runs,
                     locale = locale(encoding = "UTF-8")) |>
    rename_with(~paste0(c(startyear:endyear)), everything() ) |> mutate(RUN = 1:runs)
}

############################# Find the outflows ################################
ONLY_Outflows <- grep(paste0("loggedOutflows"), file_paths)

iD_outflows <-
  
  tibble(iD_source = file_paths[ONLY_Outflows]) |> 
  separate_wider_delim(cols = everything(),
                       names = c("Type","Scale","Polymer", "From_compartment", "to", "To_compartment"),
                       delim = "_",
                       cols_remove = FALSE) |>
  mutate(Type = "Outflow") |> 
  mutate(To_compartment = str_remove(To_compartment,"\\.csv$"))

iD_outflows <- subset(iD_outflows, select =-to)

# Add data to each row
DPMFA_outflow <- iD_outflows |>
  rowwise() |>
  mutate(Mass_Polymer_kt = list(readdelimF(root_folder = output_folder_path,
                                           FileName = iD_source,
                                           startyear = startyear,
                                           endyear = endyear,
                                           runs = runs)))

yoi <- c(2022, 2030, 2050)

DPMFA_outflow <- DPMFA_outflow %>%
  mutate(Mass_Polymer_kt = map(Mass_Polymer_kt, ~ .x[, as.character(yoi), drop = FALSE]))

################################### save #######################################
# Set data_folder to where the Rdata file should be saved 
data_folder <- "/rivm/r/E121554 LEON-T/03 - uitvoering WP3/DPMFA_textiel/Output/"

save(DPMFA_outflow, metadata,
     file = paste0(data_folder,"DPMFA_outflow_", output_folder_name,".RData"),
     compress = "xz",
     compression_level = 9)   

