# Script to make RData files from output folder with csv files. 
# Authors: Joris Quik and Anne Hids

# Load packages 
library(tidyverse)
library(readr)

################################ Load data #####################################
# set path to the 'output' folder generated by the DPMFA_NL_EU model
data_folder <- ""

# Get csv file paths
file_paths <- list.files(path=data_folder, pattern = "\\.csv$", recursive=TRUE)
file_pathsdf <- as.data.frame(file_paths)

########################### Get configurations #################################
filename <- paste0(data_folder, "/metadata.txt")
f <- readLines(filename, n=13)

ModelRunDate <- grep("Start date and time:",f, value=TRUE)
ModelRunDate <- as.Date(gsub("Start date and time: ", "", ModelRunDate), format = "%d-%m-%Y") 

startyear <- grep("Startyear: ",f, value=TRUE)
startyear <- as.numeric(gsub("Startyear: ", "", startyear))

endyear <- grep("Endyear: ",f, value=TRUE)
endyear <- as.numeric(gsub("Endyear: ", "", endyear))

runs <- grep("Runs: ",f, value=TRUE)
runs <- as.numeric(gsub("Runs: ", "", runs))

modeltype <- grep("Model type: ", f, value=TRUE)
modeltype <- gsub("Model type: ", "", modeltype)
modeltype <- as.character(modeltype)

inputfile <- grep("Maininputfile version: ", f, value=TRUE)
inputfile <- gsub("Maininputfile version: ", "", inputfile)

region <- grep("Region: ", f, value=TRUE)
region <- gsub("Region: ", "", region)

metadata <- list(ModelRunDate = ModelRunDate,
                 startyear = startyear,
                 endyear = endyear,
                 runs = runs,
                 modeltype = modeltype,
                 inputfile = inputfile,
                 region = region)

############################# Define function ##################################
readdelimF <- function(root_folder, FileName, startyear, endyear, runs){
  data <- read_delim(file = paste0(root_folder,"/",FileName),
                     col_names = FALSE,
                     delim = " ",
                     col_types = "d",
                     n_max = runs,
                     locale = locale(encoding = "UTF-8")) |>
    rename_with(~paste0(c(startyear:endyear)), everything() ) |> mutate(RUN = 1:runs)
}

############################## Find the inflows ################################
# Select the files with 'loggedInflows' in the name
ONLY_Inflows <- grep(paste0("loggedInflows"), file_paths)

iD_inflows <-
  tibble(iD_source = file_paths[ONLY_Inflows]) |> 
  separate_wider_delim(cols = everything(),
                       names = c("Type","Scale","Source","Polymer", "To_Compartment"),
                       delim = "_",
                       cols_remove = FALSE) |>
  mutate(Type = "Inflow") |> 
  mutate(To_Compartment = str_remove(To_Compartment,"\\.csv$"))

# Add data to each row
DPMFA_inflow <- iD_inflows |>
  rowwise() |>
  mutate(Mass_Polymer_kt = list(readdelimF(root_folder = data_folder,
                                           FileName = iD_source,
                                           startyear = startyear,
                                           endyear = endyear,
                                           runs = runs)))

DPMFA_inflow <-
  DPMFA_inflow |> 
  separate_wider_delim(cols = To_Compartment,
                       names = c("To_Compartment", "Material_Type"),
                       delim = " (",
                       too_few = "align_start",
                       too_many = "merge",
                       cols_remove = FALSE) |> 
  mutate(Material_Type = str_remove(Material_Type , "\\)")) |>
  mutate(Material_Type = case_when(Material_Type %in% c('macro', 'micro') ~ as.character(Material_Type),
                                   TRUE ~ NA_character_))

################################ Find the sinks ################################

ONLY_Sinks <- grep(paste0("sinks"), file_paths)

iD_sinks <-
  tibble(iD_source = file_paths[ONLY_Sinks]) |> 
  separate_wider_delim(cols = everything(),
                       names = c("Type","Scale","Source","Polymer", "To_Compartment"),
                       delim = "_",
                       cols_remove = FALSE) |>
  mutate(Type = "Sink") |> 
  mutate(To_Compartment = str_remove(To_Compartment,"\\.csv$"))

DPMFA_sink <- iD_sinks |>  
  rowwise() |>
  mutate(Mass_Polymer_kt = list(readdelimF(root_folder = data_folder,
                                                                     FileName = iD_source,
                                                                     startyear = startyear,
                                                                     endyear = endyear,
                                                                     runs = runs)))

DPMFA_sink <- DPMFA_sink |>  
  separate_wider_delim(cols = To_Compartment,
                       names = c("To_Compartment", "Material_Type"),
                       delim = " (",
                       too_few = "align_start",
                       cols_remove = FALSE) |> 
  mutate(Material_Type = str_remove(Material_Type , "\\)")) |>
  mutate(Material_Type = case_when(Material_Type %in% c('macro', 'micro') ~ as.character(Material_Type),
                                   TRUE ~ NA_character_)) 

#  group_by(Material_Type,Scale,Source,Type) #|> mutate(Material_Type =  replace_na(Material_Type, "both"))

############################# Find the outflows ################################
ONLY_Outflows <- grep(paste0("loggedOutflows"), file_paths)

iD_outflows <-
  tibble(iD_source = file_paths[ONLY_Outflows]) |> 
  separate_wider_delim(cols = everything(),
                       names = c("Type","Scale","Source","Polymer", "From_compartment", "to", "To_compartment"),
                       delim = "_",
                       cols_remove = FALSE) |>
  mutate(Type = "Outflow") |> 
  mutate(To_compartment = str_remove(To_compartment,"\\.csv$"))

iD_outflows <- subset(iD_outflows, select =-to)

# Add data to each row
DPMFA_outflow <- iD_outflows |>
  rowwise() |>
  mutate(Mass_Polymer_kt = list(readdelimF(root_folder = data_folder,
                                           FileName = iD_source,
                                           startyear = startyear,
                                           endyear = endyear,
                                           runs = runs)))

############################# Find the stocks ##################################
if (modeltype == "dpmfa"){
  ONLY_Stocks <- grep(paste0("stocks"), file_paths)

  iD_stocks <-
    tibble(iD_source = file_paths[ONLY_Stocks]) |> 
    separate_wider_delim(cols = everything(),
                         names = c("Type","Scale","Source","Polymer", "To_Compartment"),
                         delim = "_",
                         cols_remove = FALSE) |>
    mutate(Type = "Stock") |> 
    mutate(To_Compartment = str_remove(To_Compartment,"\\.csv$"))
  
  DPMFA_stock <- iD_stocks |>  
    rowwise() |>
    mutate(Mass_Polymer_kt = list(readdelimF(root_folder = data_folder,
                                             FileName = iD_source,
                                             startyear = startyear,
                                             endyear = endyear,
                                             runs = runs)))
}

################################### save #######################################
# Set data_folder to where the Rdata file should be saved 
data_folder <- "/rivm/r/E121554 LEON-T/03 - uitvoering WP3/DPMFA_output"

if (modeltype == "dpmfa"){
  save(DPMFA_inflow, DPMFA_outflow, DPMFA_sink, DPMFA_stock, metadata,
       file = paste0(data_folder,"/DPMFA_data", region, format(ModelRunDate,"%Y_%m_%d"),".RData"),
       compress = "xz",
       compression_level = 9)   
} else {
  save(DPMFA_inflow, DPMFA_outflow, DPMFA_sink, metadata,
       file = paste0(data_folder,"/PMFA_data", region, format(ModelRunDate,"%Y_%m_%d"),".RData"),
       compress = "xz",
       compression_level = 9)  
}
